apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: lb-ingress
spec:
  rules:
  - http:
      paths:
      - path: /user-service/*
        backend:
          serviceName: lb-user-service-service
          servicePort: 2006
      - path: /post-service/*
        backend:
          serviceName: lb-post-service-service
          servicePort: 2006