apiVersion: v1
kind: Service
metadata:
  name: lb-post-service-service
  namespace: p2
spec:
  type: NodePort
  selector:
    app: lb
    service: post-service
  ports:
    - protocol: TCP
      port: 2007
      targetPort: 2007