apiVersion: apps/v1
kind: Deployment 
metadate: 
  name: lb-user-service-deployment
  labels: 
    app: lb
    service: user-service
    deployment: uat
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: lb
      service: user-service
  template:
    metadata:
      labels:
        app: lb
        service:  user-service
    spec:
      containers: 
      - name: lb-user-service
        image: grc.io/PROJECT_ID/IMAGENAME:tag
        imagePullPolicy: Always
        env:
        - name: LB_HOST
          value: "10.46.0.3"
        - name: LB_DATABASE
          value: "instabytes-microservices"
        - name: LB_USER
          value: "postgres"
        - name: LB_PASSWORD 
          value: "Pink123!"
        ports:
        - containerPort: 2006
        livenessProbe:
          httpGet:
          path: /health
          port: 2006
        initialDelaySeconds: 3
        periodSeconds: 3

